### ISSUE TITLE
ReCaptcha Uploading

### ISSUE THREAD

**Issue by bizi27** [infotrex/bulk-upload-to-opensea#112]
Hey does anyone have problem with Captcha verification ? 

I must complete the verification on every uploaded NFT ? :/ is any bypass for this ?

**Comment by infotrex** [comment]
@bizi27 
download the latest file upload_captcha.py
and download buster chrome extension.
TQ

**Comment by aaaiiee** [comment]
When I did the upload_capcha.py
- click "I'm not a robot"
- click "speech to text"
- The cursor moved the left side automatically.

And then, it doesn't work.

Please, check the errors.

**Comment by BirdWord** [comment]
It doesn't work. Now we just have to find another way. This code is no longer useful.

**Comment by MedAhenna** [comment]
This software solve it and work great :
https://www.youtube.com/watch?v=poOKCqYBm6o

**Comment by Lurpigi** [comment]
> When I did the upload_capcha.py
> 
> * click "I'm not a robot"
> * click "speech to text"
> * The cursor moved the left side automatically.(?)
> 
> And then, it doesn't work.
> 
> https://drive.google.com/file/d/1aOq6Dg3MkfWx77z0mGDMe5EmoBjY1Yye/view?usp=sharing
> 
> (I installed the chrome extension "buster: captcha solver for human") Please, check the errors.

same for me

**Comment by aaaiiee** [comment]
> @bizi27 
> 
> download the latest file upload_captcha.py
> 
> and download buster chrome extension.
> 
> TQ
> 
> 

When I did the upload_capcha.py

click "I'm not a robot"
click "speech to text"

The cursor moved the left side automatically.(?)
<-- I think the process of automatically moving the cursor is unnecessary.

After clicking "speech to text", I think it would be better to leave the cursor still so that the next action can be performed automatically.

**Comment by aaaiiee** [comment]
When I did the upload_capcha.py

click "I'm not a robot"
click "speech to text"

The cursor moved the left side automatically.(?)
<-- I think the process of automatically moving the cursor is unnecessary.

After clicking "speech to text", I think it would be better to leave the cursor still so that the next action can be performed automatically.

**Comment by infotrex** [comment]
@Lurpigi 
buster options page only set to
"API key" and "Load challenge in English"
don't put any set any additional setting.

**Comment by Capi666** [comment]
> When I did the upload_capcha.py
> 
> * click "I'm not a robot"
> * click "speech to text"
> * The cursor moved the left side automatically.(?)
> 
> And then, it doesn't work.
> 
> https://drive.google.com/file/d/1aOq6Dg3MkfWx77z0mGDMe5EmoBjY1Yye/view?usp=sharing
> 
> (I installed the chrome extension "buster: captcha solver for human") Please, check the errors.

Hi,

Have you solved it? I have the problem problem --> https://github.com/infotrex/bulk-upload-to-opensea/issues/135#issuecomment-1079879656

Thanks and regards,

**Comment by Capi666** [comment]
> @Lurpigi buster options page only set to "API key" and "Load challenge in English" don't put any set any additional setting.

Thanks!! The problem was I have the option "Simulate user interaction"
