### ISSUE TITLE
March 23 OpenSea listing update.

### ISSUE THREAD

**Issue by Revmagi** [infotrex/bulk-upload-to-opensea#131]
the listing form is now blocking the date field unless you actually select the time period. 

Example of process, you need to click on the drop down and select the 6 months, and then it will adjust to its 6 month time period and then you can edit the date for the full 180 days or you can just accept the 6 months.  

If you do not specifically select the 6 months from the drop down, the end date will not edit and it defaults to 7 days.

I am trying to learn from your script how to do this selection before doing the dates, but i am not at your level yet. I assume with your knowledge this should be a quick update. I hope this helps.

**Comment by infotrex** [comment]
@Revmagi
Will update this latest script for date selection this few days.

**Comment by TeCeG** [comment]
Quick fix: 
Search:
`amount.send_keys(Keys.TAB)`

replace with: 
`amount.send_keys(Keys.TAB * 4 + Keys.SPACE)`

**Comment by Revmagi** [comment]
Thank you. I would have never guessed this. I am taking a udemy course on Python and Selenium but I am not there yet. Thanks, it is working again.

**Comment by SJFAFA** [comment]
@Revmagi @infotrex 
Hi~
In my case, the period was not set because 'month' was not entered.
This is the reason why it was minted with '7 days'.
But! This is not a script issue!

The OpenC Help Center gave me a solution.
It seems to be an internet data error.

- Clearing your browser cache
- Resetting your wallet

You can do this through the above two methods.
To reset your wallet, you can google it.

Developers, fighting!

**Comment by Revmagi** [comment]
Hello,

    I noticed mine did go back to normal the next day after a reset to my
browser. But the modifications suggested also work well.

Regards

**Comment by infotrex** [comment]
pls download the latest file(upload_captcha.py) to fixed the "Date Range" Selection. thx
