### ISSUE TITLE
Bypass Captcha PROBLEM

### ISSUE THREAD

**Issue by cristiane13091991** [infotrex/bulk-upload-to-opensea#162]
how can we solve this? (Screenshot)
[https://privatebin.support-tools.com/?a820cee807cf8c48#TGLVpRZULPtiIXytNkpOPcdiWRYU7t5v/nRtDG5GtSk=](url)

When they are uploading this message appears in the captcha and then it no longer allows you to continue uploading.

Anyone else has happened?
What is the solution?

**Comment by infotrex** [comment]
@cristiane13091991 
open the script search this  "sleeptime = random.uniform(0.5, 1.8)" change  to **sleeptime = random.uniform(0.8, 3)**

**Comment by cristiane13091991** [comment]
> 

could you explain me please
what exactly do those 2 numbers do?

Because I already made the changes and I still get the same message

**Comment by karakule3dfx** [comment]
Google marked you as a bot because of the very fast and consecutive image verifications. If you clear your browser's history completely and then turn off and on your modem, your problem will probably be solved with the new ip And those 2 numbers for to slow down codes. it sleeps the codes for as a random seconds between those two numbers. and sorry for my bad english

**Comment by infotrex** [comment]
> @infotrex
> 
> could you explain me please what exactly do those 2 numbers do?
> 
> Because I already made the changes and I still get the same message. Thanks

the 2 number is to make each step slow down a bit, to pretend i'm human upload timing :)
