### ISSUE TITLE
OpenSea MetaMask change

### ISSUE THREAD

**Issue by Revmagi** [infotrex/bulk-upload-to-opensea#165]
Opensea MetaMask change tonight makes everyone switch to the Polygon Mantic network, and this new screen makes you scroll to the bottom of the dataset before the Submit button is available to select.  I hope this is not to difficult to adjust for?? I am sure not, with your talent. Let us know if there is anything you need from us to help.  Thanks in advance.

**Comment by BorzyankiN** [comment]
Yes, I ran into the same problem today. I still use "upload_captcha.py" and everything worked fine for me until today. Could you also change the code so that it also scrolls the request signing window in metamask for "upload_captcha.py".

![1](https://user-images.githubusercontent.com/90539054/163518568-6939dc6f-2665-4adc-97e6-c8dbf189b16d.png)
![2](https://user-images.githubusercontent.com/90539054/163518570-62a12dad-4caa-4dac-aacf-f1943514a254.png)

**Comment by infotrex** [comment]
@Revmagi @BorzyankiN 
i updated the new script to file upload_captcha.py
TQ

**Comment by BorzyankiN** [comment]
> @Revmagi @BorzyankiN i updated the new script to file upload_captcha.py to fixed the polygon sign issue. TQ
@infotrex
Thank you for the quick solution of the problem. You've done a great job. I would like to thank you and send you the NFT from my new collection. Send me your wallet address.

**Comment by Revmagi** [comment]
@infotrex
I as well offer my thanks, and I have been waiting to try to get everything uploaded, but I too want to give you one of my NFTs as well, and I would appreciate if you could send me your wallet address.
