### ISSUE TITLE
got this error "TabError: inconsistent use of tabs and spaces in indentation"

### ISSUE THREAD

**Issue by Mahalance** [infotrex/bulk-upload-to-opensea#217]
I got this error 

PS D:\bulk-upload-to-opensea-main> python upload_2captcha_V2.py
  File "D:\bulk-upload-to-opensea-main\upload_2captcha_V2.py", line 836
    nft_Name = my_nft.find_element(By.XPATH, './/a//img').get_attribute('alt')
TabError: inconsistent use of tabs and spaces in indentation

how do I fix it
![bulk error1](https://user-images.githubusercontent.com/108078269/175324227-3158109c-9144-4bbf-8fff-fcc1477c17d4.png)
![bulk error2](https://user-images.githubusercontent.com/108078269/175324242-b7bbf7be-4958-431a-82c7-8bce51268a50.png)
?

**Comment by karakule3dfx** [comment]
@Mahalance
delete the spaces at the beginning of this line and move it to its previous alignment using the tab key.
I'll fix the file and upload it again. It usually happens when a space is left at the beginning of the line with the space key, not the tap key.
You can also try downloading the file again. I think it's fixed now

**Comment by Mahalance** [comment]
thank you sir, but now i got this error

selenium.common.exceptions.WebDriverException: Message: unknown error: unexpected command response        
  (Session info: chrome=103.0.5060.53)

**Comment by karakule3dfx** [comment]
I looked a bit and I think the problem is in the chrome version. you can try to downgrade or wait for the update.

**Comment by Mahalance** [comment]
ok thank you sir
